PYTHON ?= python3
NAME = HomeKitHub
STORE_INFO := release-pg3-store.txt
GIT_REMOTE ?= origin
XML_FILES = profile/*/*.xml

# apt: sudo apt-get install libxml2-utils libxml2-dev
check: xml-check

xml-check:
	xmllint --noout $(XML_FILES)

lint:
	python3 -m ruff check .

format-check:
	python3 -m ruff format --check .

black-check:
	python3 -m black --check .

test:
	python3 -m pytest -q

clean:
	python3 -c "import pathlib, shutil; r = pathlib.Path('.'); [shutil.rmtree(p, ignore_errors=True) for p in r.rglob('__pycache__') if p.is_dir()]; shutil.rmtree('.pytest_cache', ignore_errors=True); shutil.rmtree('.ruff_cache', ignore_errors=True)"
	rm -f $(NAME).zip

zip:
	rm -f $(NAME).zip
	zip -x@zip_exclude.lst -r $(NAME).zip *

# Build store zip, write $(STORE_INFO) (PG3 store hints), annotated tag v<version>, push branch + tag to $(GIT_REMOTE).
# Version = nodes/__init__.py VERSION (canonical). profile/version.txt is echoed for ISY/profile metadata.
# Run from this directory, or: make -C /path/to/udi-poly-homekit release
# Requires clean git working tree and a checked-out branch (not detached HEAD).
release:
	@set -e; \
	ROOT=$$(pwd); \
	VERSION=$$(sed -n 's/^VERSION = "\([^"]*\)"$$/\1/p' "$$ROOT/nodes/__init__.py"); \
	test -n "$$VERSION" || { echo "Could not parse VERSION from $$ROOT/nodes/__init__.py"; exit 1; }; \
	PROFILE_VERSION=$$(tr -d '\r\n' < "$$ROOT/profile/version.txt"); \
	test -n "$$PROFILE_VERSION" || { echo "$$ROOT/profile/version.txt is empty"; exit 1; }; \
	test -z "$$(git -C "$$ROOT" status --porcelain)" || { \
		echo "Working tree is not clean. Commit or stash before make release."; \
		git -C "$$ROOT" status --short; \
		exit 1; \
	}; \
	if [ "$$VERSION" != "$$PROFILE_VERSION" ]; then \
		echo "WARNING: profile/version.txt ($$PROFILE_VERSION) != nodes/__init__.py VERSION ($$VERSION)."; \
		echo "         Align profile/version.txt with nodes if ISY profile updates should match this release."; \
	fi; \
	$(MAKE) -C "$$ROOT" zip; \
	ZIP_PATH="$$ROOT/$(NAME).zip"; \
	if git -C "$$ROOT" rev-parse -q --verify "refs/tags/v$$VERSION" >/dev/null 2>&1; then \
		echo "Tag v$$VERSION already exists. Delete: git -C \"$$ROOT\" tag -d v$$VERSION"; \
		exit 1; \
	fi; \
	BRANCH=$$(git -C "$$ROOT" rev-parse --abbrev-ref HEAD); \
	if [ "$$BRANCH" = "HEAD" ]; then \
		echo "ERROR: detached HEAD. Checkout your release branch (e.g. main), then run make release."; \
		exit 1; \
	fi; \
	git -C "$$ROOT" tag -a "v$$VERSION" -m "Release $$VERSION"; \
	echo "Created annotated tag v$$VERSION."; \
	git -C "$$ROOT" push "$(GIT_REMOTE)" "$$BRANCH" "v$$VERSION"; \
	echo "Pushed $$BRANCH and v$$VERSION to $(GIT_REMOTE)."; \
	echo "Writing $$ROOT/$(STORE_INFO)"; \
	{ \
		echo "# PG3 Node Server store — generated by \`make release\` (gitignored; do not commit)"; \
		echo "#"; \
		echo "plugin_version=$$VERSION   # nodes/__init__.py VERSION — canonical (PG3 / runtime)"; \
		echo "profile_version=$$PROFILE_VERSION   # profile/version.txt — ISY profile install metadata"; \
		echo "zip_path=$$ZIP_PATH"; \
		echo "git_branch=$$BRANCH"; \
		echo "git_remote=$(GIT_REMOTE)"; \
		echo "git_tag=v$$VERSION"; \
		echo "#"; \
		echo "# Next steps:"; \
		echo "# - Upload $(NAME).zip via PG3 Developer Choose File, or host the zip and set Installation URL"; \
		echo "# - Branch + tag are on $(GIT_REMOTE) (override remote: GIT_REMOTE=... make release)."; \
	} > "$$ROOT/$(STORE_INFO)"; \
	echo ""; \
	cat "$$ROOT/$(STORE_INFO)"; \
	echo ""

.PHONY: check xml-check lint format-check black-check test clean zip release
