PYTHON ?= python3
NAME = HomeKitHub
STORE_INFO := release-pg3-store.txt
GIT_REMOTE ?= origin
# PG3 can install from a git URL + branch; these are the remote branch names we push to.
BRANCH_BETA ?= beta
BRANCH_PRODUCTION ?= production
XML_FILES = profile/*/*.xml

# apt: sudo apt-get install libxml2-utils libxml2-dev
check: xml-check

xml-check:
	xmllint --noout $(XML_FILES)

lint:
	python3 -m ruff check .

format-check:
	python3 -m ruff format --check .

black-check:
	python3 -m black --check .

test:
	python3 -m pytest -q

clean:
	python3 -c "import pathlib, shutil; r = pathlib.Path('.'); [shutil.rmtree(p, ignore_errors=True) for p in r.rglob('__pycache__') if p.is_dir()]; shutil.rmtree('.pytest_cache', ignore_errors=True); shutil.rmtree('.ruff_cache', ignore_errors=True)"
	rm -f $(NAME).zip

# Legacy / reference: local archive for manual upload or testing. Primary PG3 delivery is git branches (beta / production).
zip:
	rm -f $(NAME).zip
	zip -x@zip_exclude.lst -r $(NAME).zip *

# Push current HEAD to $(GIT_REMOTE)/$(BRANCH_BETA). Requires clean tree; not detached HEAD.
beta:
	@set -e; \
	ROOT=$$(pwd); \
	test -z "$$(git -C "$$ROOT" status --porcelain)" || { \
		echo "Working tree is not clean. Commit or stash before make beta."; \
		git -C "$$ROOT" status --short; \
		exit 1; \
	}; \
	BRANCH=$$(git -C "$$ROOT" rev-parse --abbrev-ref HEAD); \
	if [ "$$BRANCH" = "HEAD" ]; then \
		echo "ERROR: detached HEAD. Checkout a branch, then run make beta."; \
		exit 1; \
	fi; \
	REPO=$$(git -C "$$ROOT" rev-parse --show-toplevel); \
	git -C "$$ROOT" push "$(GIT_REMOTE)" HEAD:"$(BRANCH_BETA)"; \
	echo "Repository: $$REPO"; \
	echo "Branch: $(BRANCH_BETA)"; \
	echo "Pushed $$(git -C "$$ROOT" rev-parse --short HEAD) to $(GIT_REMOTE)/$(BRANCH_BETA)."

# Push current HEAD to $(GIT_REMOTE)/$(BRANCH_PRODUCTION). Requires clean tree; not detached HEAD.
production:
	@set -e; \
	ROOT=$$(pwd); \
	test -z "$$(git -C "$$ROOT" status --porcelain)" || { \
		echo "Working tree is not clean. Commit or stash before make production."; \
		git -C "$$ROOT" status --short; \
		exit 1; \
	}; \
	BRANCH=$$(git -C "$$ROOT" rev-parse --abbrev-ref HEAD); \
	if [ "$$BRANCH" = "HEAD" ]; then \
		echo "ERROR: detached HEAD. Checkout a branch, then run make production."; \
		exit 1; \
	fi; \
	REPO=$$(git -C "$$ROOT" rev-parse --show-toplevel); \
	git -C "$$ROOT" push "$(GIT_REMOTE)" HEAD:"$(BRANCH_PRODUCTION)"; \
	echo "Repository: $$REPO"; \
	echo "Branch: $(BRANCH_PRODUCTION)"; \
	echo "Pushed $$(git -C "$$ROOT" rev-parse --short HEAD) to $(GIT_REMOTE)/$(BRANCH_PRODUCTION)."

# Write $(STORE_INFO) (PG3 hints), annotated tag v<version>, push current branch + production branch ref + tag to $(GIT_REMOTE).
# Does not build a zip; use \`make zip\` only if you need a local archive.
# Version = nodes/__init__.py VERSION (canonical). profile/version.txt is echoed for ISY/profile metadata.
# Run from this directory, or: make -C /path/to/udi-poly-homekit release
# Requires clean git working tree and a checked-out branch (not detached HEAD).
release:
	@set -e; \
	ROOT=$$(pwd); \
	VERSION=$$(sed -n 's/^VERSION = "\([^"]*\)"$$/\1/p' "$$ROOT/nodes/__init__.py"); \
	test -n "$$VERSION" || { echo "Could not parse VERSION from $$ROOT/nodes/__init__.py"; exit 1; }; \
	PROFILE_VERSION=$$(tr -d '\r\n' < "$$ROOT/profile/version.txt"); \
	test -n "$$PROFILE_VERSION" || { echo "$$ROOT/profile/version.txt is empty"; exit 1; }; \
	test -z "$$(git -C "$$ROOT" status --porcelain)" || { \
		echo "Working tree is not clean. Commit or stash before make release."; \
		git -C "$$ROOT" status --short; \
		exit 1; \
	}; \
	if [ "$$VERSION" != "$$PROFILE_VERSION" ]; then \
		echo "WARNING: profile/version.txt ($$PROFILE_VERSION) != nodes/__init__.py VERSION ($$VERSION)."; \
		echo "         Align profile/version.txt with nodes if ISY profile updates should match this release."; \
	fi; \
	if git -C "$$ROOT" rev-parse -q --verify "refs/tags/v$$VERSION" >/dev/null 2>&1; then \
		echo "Tag v$$VERSION already exists. Delete: git -C \"$$ROOT\" tag -d v$$VERSION"; \
		exit 1; \
	fi; \
	BRANCH=$$(git -C "$$ROOT" rev-parse --abbrev-ref HEAD); \
	if [ "$$BRANCH" = "HEAD" ]; then \
		echo "ERROR: detached HEAD. Checkout your release branch (e.g. main), then run make release."; \
		exit 1; \
	fi; \
	git -C "$$ROOT" tag -a "v$$VERSION" -m "Release $$VERSION"; \
	echo "Created annotated tag v$$VERSION."; \
	git -C "$$ROOT" push "$(GIT_REMOTE)" "$$BRANCH" "v$$VERSION" "HEAD:$(BRANCH_PRODUCTION)"; \
	echo "Pushed $$BRANCH, $(BRANCH_PRODUCTION) @ $$(git -C "$$ROOT" rev-parse --short HEAD), and v$$VERSION to $(GIT_REMOTE)."; \
	echo "Writing $$ROOT/$(STORE_INFO)"; \
	{ \
		echo "# PG3 Node Server store — generated by \`make release\` (gitignored; do not commit)"; \
		echo "#"; \
		echo "plugin_version=$$VERSION   # nodes/__init__.py VERSION — canonical (PG3 / runtime)"; \
		echo "profile_version=$$PROFILE_VERSION   # profile/version.txt — ISY profile install metadata"; \
		echo "git_branch_production=$(BRANCH_PRODUCTION)   # point PG3 install URL at this branch (production track)"; \
		echo "git_branch_beta=$(BRANCH_BETA)   # point PG3 install URL at this branch (beta / pre-release track)"; \
		echo "git_branch_pushed=$$BRANCH   # branch pushed alongside the tag"; \
		echo "git_remote=$(GIT_REMOTE)"; \
		echo "git_tag=v$$VERSION"; \
		echo "#"; \
		echo "# Next steps:"; \
		echo "# - In PG3, set the Node Server git URL to this repo and branch \`$(BRANCH_PRODUCTION)\` (or \`$(BRANCH_BETA)\` for beta)."; \
		echo "# - Optional local zip: \`make zip\` (not used for store git installs)."; \
		echo "# - Override remote / branch names: GIT_REMOTE=... BRANCH_BETA=... BRANCH_PRODUCTION=... make release"; \
	} > "$$ROOT/$(STORE_INFO)"; \
	echo ""; \
	cat "$$ROOT/$(STORE_INFO)"; \
	echo ""

.PHONY: check xml-check lint format-check black-check test clean zip beta production release
