"""HomeKit Hub async bridge (aiohomekit + WebSocket)."""

from .bridge import (
    DATA_KEY_LAST_HAP_DISCOVER,
    DATA_KEY_PAIRINGS,
    ERR_PAIRING_FAILED,
    ERR_PAIRING_NO_TARGET,
    MqttClientSession,
    TYPED_PAIRING_SLOTS_KEY,
    assign_pairing_slot_rows,
    HomeKitHubBridge,
    normalize_hap_pin,
    slot_alias,
)
from .mqtt_topics import (
    DEFAULT_MQTT_BROKER_HOST,
    DEFAULT_MQTT_BROKER_PORT,
    MQTT_QOS_AT_LEAST_ONCE,
    MQTT_TRANSPORT_STATUS_CONNECTED,
    MQTT_TRANSPORT_STATUS_DISABLED,
    MQTT_TRANSPORT_STATUS_NOT_CONNECTED,
    client_out_event_topic,
    client_out_rpc_topic,
    clients_ingress_subscribe_pattern,
    mqtt_transport_enabled,
    normalize_hub_slug_param,
    parse_ingress_client_slug,
    sanitize_client_slug,
)

__all__ = [
    "DATA_KEY_LAST_HAP_DISCOVER",
    "DATA_KEY_PAIRINGS",
    "ERR_PAIRING_FAILED",
    "ERR_PAIRING_NO_TARGET",
    "MqttClientSession",
    "TYPED_PAIRING_SLOTS_KEY",
    "assign_pairing_slot_rows",
    "HomeKitHubBridge",
    "normalize_hap_pin",
    "slot_alias",
    "DEFAULT_MQTT_BROKER_HOST",
    "DEFAULT_MQTT_BROKER_PORT",
    "MQTT_QOS_AT_LEAST_ONCE",
    "MQTT_TRANSPORT_STATUS_CONNECTED",
    "MQTT_TRANSPORT_STATUS_DISABLED",
    "MQTT_TRANSPORT_STATUS_NOT_CONNECTED",
    "client_out_event_topic",
    "client_out_rpc_topic",
    "clients_ingress_subscribe_pattern",
    "mqtt_transport_enabled",
    "normalize_hub_slug_param",
    "parse_ingress_client_slug",
    "sanitize_client_slug",
]
